// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memory} from '../models';
import {common} from '../models';
import {context} from '../models';

export function GetHeapAddressRange():Promise<memory.AddressRange>;

export function LoadProcess(arg1:common.ProcessInformation):Promise<void>;

export function ReadMemory(arg1:number,arg2:number):Promise<Array<number>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WriteMemory(arg1:number,arg2:any):Promise<number>;
