// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProcessIDs() {
  return window['go']['process']['ProcessManager']['GetProcessIDs']();
}

export function GetProcessInformation(arg1) {
  return window['go']['process']['ProcessManager']['GetProcessInformation'](arg1);
}

export function SetContext(arg1) {
  return window['go']['process']['ProcessManager']['SetContext'](arg1);
}
