// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHeapAddressRange() {
  return window['go']['memman']['MemoryManager']['GetHeapAddressRange']();
}

export function LoadProcess(arg1) {
  return window['go']['memman']['MemoryManager']['LoadProcess'](arg1);
}

export function ReadMemory(arg1, arg2) {
  return window['go']['memman']['MemoryManager']['ReadMemory'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['memman']['MemoryManager']['SetContext'](arg1);
}

export function WriteMemory(arg1, arg2) {
  return window['go']['memman']['MemoryManager']['WriteMemory'](arg1, arg2);
}
