// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRunningProcesses() {
  return window['go']['main']['App']['GetAllRunningProcesses']();
}

export function GetMemoryManager() {
  return window['go']['main']['App']['GetMemoryManager']();
}

export function GetProcessManager() {
  return window['go']['main']['App']['GetProcessManager']();
}
