// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memman} from '../models';
import {procman} from '../models';

export function GetAllRunningProcesses():Promise<Array<string>>;

export function GetMemoryManager():Promise<memman.MemoryManager>;

export function GetProcessManager():Promise<procman.ProcessManager>;
