// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {memory} from '../models';
import {process} from '../models';
import {system} from '../models';

export function GetAllRunningProcesses():Promise<Array<string>>;

export function GetMemoryManager():Promise<memory.MemoryManager>;

export function GetProcessManager():Promise<process.ProcessManager>;

export function GetSystemInformation():Promise<system.SystemInformation>;
